const loginCard=document.querySelector('#loginCard'),adminApp=document.querySelector('#adminApp'),loginForm=document.querySelector('#loginForm'),loginMessage=document.querySelector('#loginMessage'),editor=document.querySelector('#catalogEditor'),saveStatus=document.querySelector('#saveStatus'),uploadStatus=document.querySelector('#uploadStatus');
const setVisible=authenticated=>{loginCard.hidden=authenticated;adminApp.hidden=!authenticated};
async function api(path,options={}){const response=await fetch(path,options),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Não foi possível concluir a operação.');return body}
const localCollections=()=>typeof getLocalCatalogCollections==='function'?getLocalCatalogCollections():[];
async function optimizeImage(file){const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'}),scale=Math.min(1,1500/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.82));return new File([blob],file.name.replace(/\.[^.]+$/,'.webp'),{type:'image/webp'})}
async function loadCatalog(){const catalog=await api('/api/catalog',{cache:'no-store'});editor.value=JSON.stringify(catalog.collections?.length?catalog.collections:localCollections(),null,2)}
loginForm.addEventListener('submit',async event=>{event.preventDefault();loginMessage.textContent='';try{await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:document.querySelector('#password').value})});setVisible(true);await loadCatalog()}catch(error){loginMessage.textContent=error.message}});
document.querySelector('#logout').addEventListener('click',async()=>{await api('/api/logout',{method:'POST'});loginForm.reset();setVisible(false)});
document.querySelector('#loadLocal').addEventListener('click',()=>{editor.value=JSON.stringify(localCollections(),null,2);saveStatus.textContent='Catálogo local carregado. Revise e clique em Salvar catálogo.'});
document.querySelector('#saveCatalog').addEventListener('click',async()=>{saveStatus.textContent='';try{const collections=JSON.parse(editor.value);if(!Array.isArray(collections))throw new Error('O catálogo precisa ser uma lista de coleções.');await api('/api/catalog',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({collections})});saveStatus.textContent='Catálogo salvo e publicado.'}catch(error){saveStatus.textContent=error.message}});
document.querySelector('#imageInput').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;uploadStatus.textContent='Otimizando e enviando imagem...';try{const form=new FormData();form.append('file',await optimizeImage(file));const{url}=await api('/api/upload',{method:'POST',body:form}),start=editor.selectionStart;editor.setRangeText(`\"${url}\"`,start,editor.selectionEnd,'end');uploadStatus.textContent='Imagem enviada; URL inserida no editor.'}catch(error){uploadStatus.textContent=error.message}event.target.value=''});
(async()=>{try{const{authenticated}=await api('/api/session',{cache:'no-store'});setVisible(authenticated);if(authenticated)await loadCatalog()}catch{setVisible(false)}})();
